### ISSUE TITLE
execution stop

### ISSUE THREAD

**Issue by moaeddy** [Dviros/CredsLeaker#2]
windows keeps coming even when correct information is entered. anyway to workaround this?

**Comment by Dviros** [comment]
Hey @moaeddy, can you please share more details? Where did you execute it (WORKGROUP or domain machine)? Do you have a connection to the DC?
Thanks

**Comment by moaeddy** [comment]
WORKGROUP

**Comment by Dviros** [comment]
Hi,
Please see https://github.com/Dviros/CredsLeaker/issues/1
