### ISSUE TITLE
Can we stack login prompt box on top of every window

### ISSUE THREAD

**Issue by usama7628674** [Dviros/CredsLeaker#7]
@Dviros  The `System.Windows.Forms.dll` has a property `Form.TopMost` to stack form box on top of every window but here we're calling Windows API and it does not provide any such property.Any way we can do this.

**Comment by Dviros** [comment]
I'll check it.

**Comment by usama7628674** [comment]
@Dviros Can we do it on SecureDesktop?

**Comment by Dviros** [comment]
@usama7628674 I'm not so sure it can work with the credentials picker:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.topmost?view=netframework-4.8
It's much more relevant for a .NET form.
